## Replicacao dados de cancer de mama utilizando pseudo-valores para S(t)

Formula dos pseudo-valores para S(t):
$$Y_{ij} = n\hat{S}_{KM}(t_j) - (n-1)\hat{S}_{KM}^{(-i)}(t_j)$$

In [2]:
# Carregando bibliotecas

library(survival)
library(dplyr)
library(tidyr)

In [ ]:
dados_treino <- read.csv("../../../dados/dados-processados/dados_treino.csv", stringsAsFactors = FALSE)
dados_teste <- read.csv("../../../dados/dados-processados/dados_teste.csv", stringsAsFactors = FALSE)

covariaveis_rede <- setdiff(
  intersect(names(dados_treino), names(dados_teste)),
  c("id_paciente", "tempo", "delta_t")
)

prepara_base <- function(df, set_label, covariaveis) {
  base <- df %>%
    select(id_paciente, tempo, delta_t, all_of(covariaveis)) %>%
    mutate(
      ID = as.numeric(id_paciente),
      FAILTIME = as.numeric(tempo),
      FAILCENS = as.numeric(delta_t),
      SET = set_label
    ) %>%
    select(ID, FAILTIME, FAILCENS, all_of(covariaveis), SET) %>%
    filter(FAILTIME > 0, !is.na(FAILCENS))
  # Imputação de dados faltantes
  for (nm in covariaveis) {
    if (is.numeric(base[[nm]])) {
      med <- stats::median(base[[nm]], na.rm = TRUE)
      if (is.na(med)) med <- 0
      base[[nm]][is.na(base[[nm]])] <- med
    } else {
      base[[nm]] <- as.character(base[[nm]])
      base[[nm]][is.na(base[[nm]]) | base[[nm]] == ""] <- "NA"
    }
  }

  base
}

cancer_mama <- bind_rows(
  prepara_base(dados_treino, "train", covariaveis_rede),
  prepara_base(dados_teste, "test", covariaveis_rede)
) %>%
  arrange(ID)

n_distinct(cancer_mama$ID)
head(cancer_mama)

[1] 6076

  ID FAILTIME FAILCENS rhc_raca_cor instrucao est_cong
1 1  16       1        Branca       0         2
2 2  60       1        Não Branca   0         2
3 3   1       1        Não Branca   0         2
4 4  13       1        Não Branca   0         1
5 5  69       1        Não Branca   1         2
6 6   7       1        Não Branca   1         2
  rhc_historico_familiar_cancer rhc_historico_alcool rhc_historico_tabaco
1 Não                           NA                   Nunca
2 Não                           NA                   Sim
3 NA                            NA                   NA
4 Sim                           NA                   NA
5 NA                            NA                   NA
6 NA                            NA                   NA
  rhc_origem_encamiamento ⋯ rhc_diagnostico_e_tratamentos_anteriores
1 Não SUS                 ⋯ Com diag./Sem trat.
2 SUS                     ⋯ Sem diag./Sem trat.
3 SUS                     ⋯ Sem diag./Sem trat.
4 SUS                     ⋯ Com diag./Sem trat.
5 SUS                     ⋯ Com diag./Sem trat.
6 SUS                     ⋯ Sem diag./Sem trat.
  rhc_idade_no_diagnostico_tumor macroregiao pndr_renda  faixa_etcat ano
1 73                             3           Média Renda 5           2014
2 75                             3           Média Renda 5           2012
3 93                             1           Alta Renda  5           2018
4 29                             2           Média Renda 1           2013
5 38                             1           Baixa Renda 1           2010
6 43                             1           Alta Renda  2           2017
  tipo_hcido diff_data_1consulta diff_data_tratamento SET
1 8500         12                42                   train
2 8500       -104                69                   train
3 8500        -41                 0                   test
4 8500         19                33                   test
5 8500         83                99                   train
6 min100      -10                46                   train

In [4]:
grade_tempos <- quantile(
  cancer_mama$FAILTIME[cancer_mama$FAILCENS > 0],
  probs = seq(0.05, 0.95, length.out = 10),
  names = FALSE
)

grade_tempos

 [1]  2.0  8.0 12.0 16.0 21.1 28.0 34.0 42.0 53.0 78.0

In [5]:
get_sobrevivencia <- function(fit, tempos) {
  summary(fit, times = tempos, extend = TRUE)$surv
}

calcula_pseudo <- function(time, status, tempos) {
  n <- length(time)
  m <- length(tempos)

  fit_completo <- survfit(Surv(time, status) ~ 1)
  s_completo <- get_sobrevivencia(fit_completo, tempos)

  pseudo <- matrix(NA, nrow = n, ncol = m)

  for (i in seq_len(n)) {
    fit_sem_i <- survfit(Surv(time[-i], status[-i]) ~ 1)
    s_sem_i <- get_sobrevivencia(fit_sem_i, tempos)
    pseudo[i, ] <- n * s_completo - (n - 1) * s_sem_i
  }

  colnames(pseudo) <- paste0("t_", round(tempos, 6))
  pseudo
}

pseudo_valores <- calcula_pseudo(
  time = cancer_mama$FAILTIME,
  status = cancer_mama$FAILCENS,
  tempos = grade_tempos
)

n <- nrow(cancer_mama)
m <- length(grade_tempos)

base_expandida <- cancer_mama[rep(seq_len(n), each = m), c("ID", covariaveis_rede, "SET"), drop = FALSE]

entrada_rede <- base_expandida %>%
  mutate(
    TIME = rep(grade_tempos, times = n),
    PSEUDO = as.vector(t(pseudo_valores))
  ) %>%
  select(ID, all_of(covariaveis_rede), TIME, PSEUDO, SET)

head(entrada_rede, 20)

    ID rhc_raca_cor instrucao est_cong rhc_historico_familiar_cancer
1   1  Branca       0         2        Não
1.1 1  Branca       0         2        Não
1.2 1  Branca       0         2        Não
1.3 1  Branca       0         2        Não
1.4 1  Branca       0         2        Não
1.5 1  Branca       0         2        Não
1.6 1  Branca       0         2        Não
1.7 1  Branca       0         2        Não
1.8 1  Branca       0         2        Não
1.9 1  Branca       0         2        Não
2   2  Não Branca   0         2        Não
2.1 2  Não Branca   0         2        Não
2.2 2  Não Branca   0         2        Não
2.3 2  Não Branca   0         2        Não
2.4 2  Não Branca   0         2        Não
2.5 2  Não Branca   0         2        Não
2.6 2  Não Branca   0         2        Não
2.7 2  Não Branca   0         2        Não
2.8 2  Não Branca   0         2        Não
2.9 2  Não Branca   0         2        Não
    rhc_historico_alcool rhc_historico_tabaco rhc_origem_encamiamento
1   NA                   Nunca                Não SUS
1.1 NA                   Nunca                Não SUS
1.2 NA                   Nunca                Não SUS
1.3 NA                   Nunca                Não SUS
1.4 NA                   Nunca                Não SUS
1.5 NA                   Nunca                Não SUS
1.6 NA                   Nunca                Não SUS
1.7 NA                   Nunca                Não SUS
1.8 NA                   Nunca                Não SUS
1.9 NA                   Nunca                Não SUS
2   NA                   Sim                  SUS
2.1 NA                   Sim                  SUS
2.2 NA                   Sim                  SUS
2.3 NA                   Sim                  SUS
2.4 NA                   Sim                  SUS
2.5 NA                   Sim                  SUS
2.6 NA                   Sim                  SUS
2.7 NA                   Sim                  SUS
2.8 NA                   Sim                  SUS
2.9 NA                   Sim                  SUS
    rhc_estadiamento_clinico
1   NA
1.1 NA
1.2 NA
1.3 NA
1.4 NA
1.5 NA
1.6 NA
1.7 NA
1.8 NA
1.9 NA
2   III e IV
2.1 III e IV
2.2 III e IV
2.3 III e IV
2.4 III e IV
2.5 III e IV
2.6 III e IV
2.7 III e IV
2.8 III e IV
2.9 III e IV
    rhc_primeiro_tratamento_recebido_no_hospital_nenhum ⋯ macroregiao
1   Não                                                 ⋯ 3
1.1 Não                                                 ⋯ 3
1.2 Não                                                 ⋯ 3
1.3 Não                                                 ⋯ 3
1.4 Não                                                 ⋯ 3
1.5 Não                                                 ⋯ 3
1.6 Não                                                 ⋯ 3
1.7 Não                                                 ⋯ 3
1.8 Não                                                 ⋯ 3
1.9 Não                                                 ⋯ 3
2   Não                                                 ⋯ 3
2.1 Não                                                 ⋯ 3
2.2 Não                                                 ⋯ 3
2.3 Não                                                 ⋯ 3
2.4 Não                                                 ⋯ 3
2.5 Não                                                 ⋯ 3
2.6 Não                                                 ⋯ 3
2.7 Não                                                 ⋯ 3
2.8 Não                                                 ⋯ 3
2.9 Não                                                 ⋯ 3
    pndr_renda  faixa_etcat ano  tipo_hcido diff_data_1consulta
1   Média Renda 5           2014 8500         12
1.1 Média Renda 5           2014 8500         12
1.2 Média Renda 5           2014 8500         12
1.3 Média Renda 5           2014 8500         12
1.4 Média Renda 5           2014 8500         12
1.5 Média Renda 5           2014 8500         12
1.6 Média Renda 5           2014 8500         12
1.7 Média Renda 5           2014 8500         12
1.8 Média Renda 5           2014 8500         12
1.9 Média Renda 5           2014 8500         12
2   Média Renda 5           2012 8500       -104
2.1 Média Renda 5           2012 8500       -104
2.2 Média Renda 5           2012 8500       -104
2.3 Média Renda 5           2012 8500       -104
2.4 Média Renda 5           2012 8500       -104
2.5 Média Renda 5           2012 8500       -104
2.6 Média Renda 5           2012 8500       -104
2.7 Média Renda 5           2012 8500       -104
2.8 Média Renda 5           2012 8500       -104
2.9 Média Renda 5           2012 8500       -104
    diff_data_tratamento TIME PSEUDO      SET
1   42                    2.0  1.00000538 train
1.1 42                    8.0  1.00013470 train
1.2 42                   12.0  1.00036735 train
1.3 42                   16.0 -0.03903342 train
1.4 42                   21.1 -0.03859288 train
1.5 42                   28.0 -0.03803687 train
1.6 42                   34.0 -0.03742833 train
1.7 42                   42.0 -0.03683670 train
1.8 42                   53.0 -0.03610448 train
1.9 42                   78.0 -0.03511662 train
2   69                    2.0  1.00000538 train
2.1 69                    8.0  1.00013470 train
2.2 69                   12.0  1.00036735 train
2.3 69                   16.0  1.00078465 train
2.4 69                   21.1  1.00142649 train
2.5 69                   28.0  1.00290414 train
2.6 69                   34.0  1.00594016 train
2.7 69                   42.0  1.01084559 train
2.8 69                   53.0  1.02136325 train
2.9 69                   78.0 -0.83481961 train

In [6]:
dir_entrada <- file.path("..", "dados", "entrada")
dir.create(dir_entrada, recursive = TRUE, showWarnings = FALSE)

write.csv(entrada_rede, file.path(dir_entrada, "entrada_rede.csv"), row.names = FALSE)
write.csv(cancer_mama, file.path(dir_entrada, "cancer_mama_bruto.csv"), row.names = FALSE)

list.files(dir_entrada)

[1] "cancer_mama_bruto.csv" "entrada_rede.csv"